#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

using namespace std;

enum TokenType {
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,

  IDENTIFIER, STRING, NUMBER,

  AND, CLASS, ELSE, FALSE_TOK, FUN, FOR, IF, NIL, OR,
  PRINT, RETURN, SUPER, THIS, TRUE_TOK, VAR, WHILE,

  EOF_TOK
};

#endif // TOKEN_TYPE_H
